### ISSUE TITLE
Explanation of the coverage command

### ISSUE THREAD

**Issue by prbaron** [Izhaki/Typescript-Mocha-Istanbul-Boilerplate#1]
Hi,

Good job on doing a code coverage to Typescript. Is it possible to get more explanation on how you achieve it ? I'm thinking of this line 

```
"test:coverage": "ts-node node_modules/istanbul/lib/cli.js cover -e .ts  -x \"*.d.ts\" -x \"*.spec.ts\" _mocha -- --compilers ts:ts-node/register -R spec src/**/*.spec.ts"
```

Best regards.

**Comment by Izhaki** [comment]
Let's break it down:
- `ts-node` - allows the execution of TypeScript files with node, without the need for explicit transpilation.
- `node_modules/istanbul/lib/cli.js cover` - use istanbul's cover command 
- `-e .ts` - the extension of files to include. The docs are pretty terrible, but if you dig the docs/source deep enough you'll see this option.
- `-x \"*.d.ts\" -x \"*.spec.ts\"` - file patterns to exclude
- Now we need to provide istanbul with the test runner:
- `_mocha` - we use the 'test' version of mocha, which use serial rather than parallel approach.
- `--` - the following parameters are for the test runner, not istanbul.
- `--compilers ts:ts-node/register` - use this compiler with mocha.
- `-R spec` - specify reporter.
- `src/**/*.spec.ts` - the specs to run.

Hope this helps.

**Comment by prbaron** [comment]
Awesome !
